export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_ERROR = "FETCH_ERROR";

export const START_BURGER_PURCHASE = "START_BURGER_PURCHASE";
export const INIT_BURGER_PURCHASE = "INIT_BURGER_PURCHASE";
export const BURGER_PURCHASE_SUCCESS = "BURGER_PURCHASE_SUCCESS";
export const BURGER_PURCHASE_FAILURE = "BURGER_PURCHASE_FAILURE";
export const INIT_PURCHASE = "INIT_PURCHASE";

export const INIT_FETCH_ORDER="INIT_FETCH_ORDER";
export const FETCH_ORDER_SUCCESS="FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILURE= "FETCH_ORDER_FAILURE";

export const AUTH_START = "AUTH_START"; 
export const AUTH_SUCCESS = "AUTH_SUCCESS"; 
export const AUTH_FAIL = "AUTH_FAIL"; 

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH="SET_AUTH_REDIRECT_PATH";
